### ISSUE TITLE
Trouble opening the solution file in VS 2015

### ISSUE THREAD

**Issue by sambengtson** [sonvister/Binance#10]
After cloning the project, having some trouble opening the solution file in VS 2015.  I'm curious to hear if your build environment is significantly different than mine?

Attached is the specific error that I'm receiving

I'm also having a similar error while using the nuget package while targeting .NET 4.5.2.  But that may be related to this
![capture](https://user-images.githubusercontent.com/5069583/34456884-53061486-ed67-11e7-90d6-4a74f4031f5f.PNG)

**Comment by sonvister** [comment]
For development I use the latest [Visual Studio Community 2017](https://www.visualstudio.com/vs/community/) (version 15.5.2). Multiple versions of VS can co-exist on the same system (assuming you have the HDD space). I do not plan to support the VS 2015 build environment.

As for the NuGet package, as stated in the description, this is a [.NET Standard 2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) project.
