### ISSUE TITLE
How to GetOrderAsync including the fills (FULL)?

### ISSUE THREAD

**Issue by rodyla** [sonvister/Binance#105]
Is it possible to get a order with all the fills? The Binance API requires to send a response parameter FULL. Is that possible at the moment? Tnx!

**Comment by sonvister** [comment]
Hi @rodyla, FULL is the default response type for all *new* orders with this [API](https://github.com/sonvister/Binance/blob/master/src/Binance/Api/BinanceApi.cs#L455) where the fills are returned in the [Order](https://github.com/sonvister/Binance/blob/master/src/Binance/Account/Orders/Order.cs#L92) response. There is no get order with fills capability in the official [Binance API](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#query-order-user_data) last I looked.

**Comment by rodyla** [comment]
Ok tnx! I was wondering why fills was empty on query an order, now I know :-)
