### ISSUE TITLE
Symbol Cache contains null entris for BCH

### ISSUE THREAD

**Issue by bobby-ko** [sonvister/Binance#106]
After the BCH hard fork the Symbol.Cache will now contain null entries after calling UpdateCacheAsync. Seems to be due to this - Symbol.AddCacheRedirections. This also causes Null reference exceptions when calling "GetOpenOrdersAsync"

**Comment by sonvister** [comment]
@bobby-coinstorm, thanks for mentioning. Please let me know if [v0.2.0-beta8](https://github.com/sonvister/Binance/releases/tag/v0.2.0-beta8) resolves this issue.

**Comment by bobby-ko** [comment]
All good now! Tnx!
