### ISSUE TITLE
Problem with NewBinanceWApiException

### ISSUE THREAD

**Issue by khoofard** [sonvister/Binance#108]
I tried a withdrawal using API Keys that did not have withdrawal permissions. The exception being returned from this method does not include the "You don't have permission." message in the JSON variable. So unless I debugged it, I could not tell why my withdrawal failed.

Here is a screen shot from debugging that shows the key fields in the immediate window.

![image](https://user-images.githubusercontent.com/36492246/49061671-b3a66000-f254-11e8-80d0-a70b5a90614b.png)

Absolutely love this code! Thank you so much!

**Comment by sonvister** [comment]
@khoofard, I'm glad you enjoy working with the code and thanks for this information.

I'll make the following change:
```C#
if (!string.IsNullOrWhiteSpace(error))
{
    if (error.IsJsonObject())
    {
        try // to parse server error response.
        {
            var jError = JObject.Parse(error);

            errorCode = jError["code"]?.Value<int>() ?? 0;
            errorMessage = jError["msg"]?.Value<string>();
        }
        catch (Exception e)
        {
            _logger?.LogError(e, $"{nameof(BinanceApi)}.{methodName} failed to parse server error response: \"{error}\"");
            throw;
        }
    }
    else
    {
        errorMessage = error;
    }
}
```

**Comment by sonvister** [comment]
Test results using `BinanceConsoleApp`:

```
withdraw btc 3JjG3tRR1dx98UJyNdpzpkrxRjXmPfQHk9 0.01
fail: Binance.BinanceApi[0]
      BinanceApi.WithdrawAsync: Failed (asset: "BTC") - "You don't have permission." [NO CODE]

! Exception: BinanceApi.WithdrawAsync: Failed (asset: "BTC") - "You don't have permission." [NO CODE]
```

This change will be in **0.2.0-beta9**... but, I think I'll wait a bit before creating that release.

**Comment by khoofard** [comment]
Thank you for such a quick response. What is the best way to contact you? Here? Email?
