### ISSUE TITLE
[Question]: How do I track an order

### ISSUE THREAD

**Issue by wireless90** [sonvister/Binance#117]
After I set an order and get its order ID, how do I get notified once it is completed using web socket. 

I use CandlestickWebSocketClient for candlesticks and AggregateTradeWebSocketClient for trade. 

What do I use for my Orders?

**Comment by sonvister** [comment]
@wireless90, you can use the [`IUserDataWebSocketClient`](https://github.com/sonvister/Binance/blob/master/src/Binance/WebSocket/Client/IUserDataWebSocketClient.cs) or [`IUserDataWebSocketManager`](https://github.com/sonvister/Binance/blob/master/src/Binance/WebSocket/Manager/IUserDataWebSocketManager.cs) and listen for `OrderUpdate` events. The later manages the listen key for you.

More Information:
- An [example](https://github.com/sonvister/Binance/blob/master/samples/BinanceConsoleApp/Examples/AccountBalancesExample.cs) using [`IUserDataWebSocketManager`](https://github.com/sonvister/Binance/blob/master/src/Binance/WebSocket/Manager/IUserDataWebSocketManager.cs).
- The relevant official Binance Web API [documentation](https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md).

**Comment by wireless90** [comment]
Thanks! Perfect. Done
