### ISSUE TITLE
Timestamp error

### ISSUE THREAD

**Issue by Mithgroth** [sonvister/Binance#12]
Helloes,
the first call to the API always throws the timestamp exception:

```
using (var user = new BinanceApiUser("key", "secret"))
{
      var api = new BinanceApi();
      var order = await api.GetAccountInfoAsync(user);
      var deposits = await api.GetDepositsAsync(user, "BTC");
      var withdrawals = await api.GetWithdrawalsAsync(user, "BTC");
      var account = await api.GetTradesAsync(user, Symbol.XVG_BTC);
}
```
![screenshot_2](https://user-images.githubusercontent.com/4046159/34483487-d20eb23c-efcf-11e7-82f2-b2c262cdac10.jpg)

It doesn't appear when continued and called for the second time and so on.

I can always handle the exception and do the call again as a workaround, however you might want to fix this.

**Comment by sonvister** [comment]
@Mithgroth, what version of the Binance library are you using? Based on the code you provided you are using a version prior to 0.2.0-alpha.3 (*the GetTradesAsync method shown is now GetAccountTradesAsync*). Please **update to the latest pre-release** and see if the error persists. There have been modifications to the timestamp offset calculation to provide more reliable time synchronization.

With the latest Binance library, I ran the following multiple times without exception:

```C#
using (var user = new BinanceApiUser("key", "secret"))
{
    var api = new BinanceApi();
    var account = await api.GetAccountInfoAsync(user);
    var deposits = await api.GetDepositsAsync(user, Asset.BTC);
    var withdrawals = await api.GetWithdrawalsAsync(user, Asset.BTC);
    var trades = await api.GetAccountTradesAsync(user, Symbol.XVG_BTC);
}
```

**Comment by zgrkpnr** [comment]
@Mithgroth I had the same problem and diagnosed the problem. The problem occurs when there are too many async tasks scheduled. This sometimes causes the function which gets time from server to wait for a long time before getting executed. Of course, meanwhile server time changes.

You can try to minimize unnecessary concurrency in your application. Or do as little work as possible in , for example, websocket callbacks.

Hope it helps.
