### ISSUE TITLE
[newbie_Question] what to put for cancellation token?

### ISSUE THREAD

**Issue by OutkastedOne** [sonvister/Binance#121]
i have a rather newbie question, im new to coding so please be patient, im not the brightest spark to have been thrown off the grinder.

i have almost lost my mind 3 times now, and no matter how hard i use my google foo i cannot find out what to type into the "cancellation token" part of "GetCandlesticksAsync"

here is what i have at the moment:
`BinanceKlineData TestData = await PriceUpdater.GetCandlesticksAsync("BTCUSDT",CandlestickInterval.Minute,0,serverTime,serverTime,¿WhatGoesHere¿).Result;`

i tried "CancellationToken token = default" but it just says the following
" 'CancellationToken' is a type, which is not valid in the given context "

the idea is that the program will show the "open,close,high,low,price,volume,etc", do not want it to make trades with it or have it trade for me, just a price tracker which can show me the % my position is up or down, the rest i just wanted to play with, i figured out how to use the "getpriceasync" which did what i wanted regarding the price and shows my position is either up or down but i would like to be able to play around with the open,close,high,low,etc.

**Comment by sonvister** [comment]
If you don't have a token, don't pass anything.

**Comment by sonvister** [comment]
Also, you don't use '.Result' with await.

**Comment by OutkastedOne** [comment]
ok thanks, ill have a play with it and just leave it out, thanks mate
