### ISSUE TITLE
Binance changes will affect this api...

### ISSUE THREAD

**Issue by evo11x** [sonvister/Binance#124]
Binance will stop services on the following API endpoints starting from 2019/08/31 23:59 (UTC):

GET api/v1/order
GET api/v1/openOrders
POST api/v1/order
DELETE api/v1/order
GET api/v1/allOrders
GET api/v1/account
GET api/v1/myTrades
If you are currently using any of the above API endpoints, please ensure that you leave sufficient time to change or migrate to other endpoints to not affect your normal trading. We recommend that you use the GET api/v3 endpoint. 

Our apps will stop functioning, can we migrate this to the new api in this timeframe?

**Comment by alikalfaoglu** [comment]
As far as I can see, these apis no longer used. Not found any usage in source. I mean, v3 versions are already used..

**Comment by evo11x** [comment]
ok, that's good :)
