### ISSUE TITLE
Unit test fix for commit 80dcb6ed869de65bc767edda10ead09fce0a8455

### ISSUE THREAD

**Issue by bradsavon** [sonvister/Binance#14]
Apply patch @sonvister :

From f52bd81d64f1ed5ad8e374938593c893d8b7ce92 Mon Sep 17 00:00:00 2001
From: brad <brad.savon@gmail.com>
Date: Wed, 3 Jan 2018 17:18:09 -0500
Subject: [PATCH] update unit test to match
 80dcb6ed869de65bc767edda10ead09fce0a8455 implementation

\---
 test/Binance.Tests/Market/SymbolStatisticsTest.cs | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/test/Binance.Tests/Market/SymbolStatisticsTest.cs b/test/Binance.Tests/Market/SymbolStatisticsTest.cs
index a078bbf..363dd9b 100644
\--- a/test/Binance.Tests/Market/SymbolStatisticsTest.cs
\+++ b/test/Binance.Tests/Market/SymbolStatisticsTest.cs
@@ -61,7 +61,8 @@ namespace Binance.Tests.Market
             Assert.Throws<ArgumentException>("lastTradeId", () => new SymbolStatistics(symbol, period, priceChange, priceChangePercent, weightedAveragePrice, previousClosePrice, lastPrice, lastQuantity, bidPrice, bidQuantity, askPrice, askQuantity, openPrice, highPrice, lowPrice, volume, quoteVolume, openTime, closeTime, lastTradeId, firstTradeId, tradeCount));
 \
             Assert.Throws<ArgumentException>("tradeCount", () => new SymbolStatistics(symbol, period, priceChange, priceChangePercent, weightedAveragePrice, previousClosePrice, lastPrice, lastQuantity, bidPrice, bidQuantity, askPrice, askQuantity, openPrice, highPrice, lowPrice, volume, quoteVolume, openTime, closeTime, firstTradeId, lastTradeId, -1));
\-            Assert.Throws<ArgumentException>("tradeCount", () => new SymbolStatistics(symbol, period, priceChange, priceChangePercent, weightedAveragePrice, previousClosePrice, lastPrice, lastQuantity, bidPrice, bidQuantity, askPrice, askQuantity, openPrice, highPrice, lowPrice, volume, quoteVolume, openTime, closeTime, firstTradeId, lastTradeId, tradeCount + 1));
\+            // TODO: Binance API stream occasionally returns invalid trade counts...
\+            //Assert.Throws<ArgumentException>("tradeCount", () => new SymbolStatistics(symbol, period, priceChange, priceChangePercent, weightedAveragePrice, previousClosePrice, lastPrice, lastQuantity, bidPrice, bidQuantity, askPrice, askQuantity, openPrice, highPrice, lowPrice, volume, quoteVolume, openTime, closeTime, firstTradeId, lastTradeId, tradeCount + 1));
         }
 \
         [Fact]
\-- 
2.9.2.windows.1

**Comment by sonvister** [comment]
Thanks. I saw that too, I just didn't push my changes last night. Done.
