### ISSUE TITLE
BinanceHttpException on Win Server 2016.

### ISSUE THREAD

**Issue by sanchoflat** [sonvister/Binance#15]
Hi, I have another problem, maybe you now what's the problem. 
When I use something like **`GetOrderBookTopAsync()`** or -**`GetOpenOrdersAsync()`** on Win server 2016 (I install VS 2017 and .NET Core 2.0) it returns sometimes **`Binance.Api.BinanceHttpException: [Forbidden]: 'Forbidden' - [NO MSG] [NO CODE]`**. When i retry code - it returns the same error. I'm waiting about 1-2 minutes and problem dissapears.
I'm trying to re-create this problem on local machine - no result. When it crashes on server - it passed on local machine.

I compare request for two machines - they are the same.
But one difference - server send's and recieve's requests 4-5 times faster.

Thx.

**Comment by sanchoflat** [comment]
I created some tests:
```
while (true) {
	try	{
		var orders = await _binanceApi.GetOrderBookTopAsync(Symbol.BTC_USDT);
		Console.WriteLine($"[{c++}]");
	}
	catch (Exception e)
	{
		Console.WriteLine(e.Message);
		Thread.Sleep(2000);
	}
}
```

Win Server create 1200 (binance limit) request in 40-55 seconds. When I create 1200 request in less then 1 minute - api waits answer. After 3 laps (3600 requests) - it fails with **`403 Forbidden`** error. 3.5-5 minutes it returns error and then it work again. If I try to make this test on another machine when first one fails - it works. I thinks it appears when i have to much requests.

**Comment by sonvister** [comment]
@sanchoflat, I'm not sure why you would see HTTP 403 intermittently. Based on the official [documentation](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md) you should be getting **HTTP 429** then **HTTP 418** if you exceed the request rate limit(s).
