### ISSUE TITLE
Nuget Package for .NET Framework

### ISSUE THREAD

**Issue by zgrkpnr** [sonvister/Binance#16]
Hi. For now, .NET Standard and .NET Core have limited application domain. Is it possible that the library can also be published on Nuget as .NET Framework build, too? 

We cannot use .NET Standard on WPF yet. And UWP only works on Windows 10.

**Comment by sonvister** [comment]
@zgrkpnr, I have updated the project to also target **.NET Framework 4.7.1** available in **v0.2.0-alpha.11**. Let me know if this works for you.

**Comment by zgrkpnr** [comment]
@sonvister It works.
