### ISSUE TITLE
Extension With MVC Web Application

### ISSUE THREAD

**Issue by turgayacar** [sonvister/Binance#18]
Greetings;
Your plug-in is really very successful. I used it in my desktop application, but I can not use it in my MVC application.

var client = api.HttpClient; // ... property on IBinanceApi.

I can not find the part.
 I have not found any simple link and usage examples in the document section for MVC web.
Could you tell me how to use it on the web side?
When I write it under ActionResult, it is waiting for processing (hours) but I can not get anything.

**Comment by sonvister** [comment]
@turgayacar, I created a couple of minimal sample web applications (ASP.NET Core and .NET Framework MVC). I used Visual Studio Community 2017 templates and modified the HomeController to display the current Binance server time. They each work as expected. Hope this helps.
