### ISSUE TITLE
Binance.Api.BinanceHttpException: '[BadRequest]: 'Bad Request' - Illegal characters found in parameter 'type'; legal range is '^[a-zA-Z_]{1,20}$'. (-1100)'

### ISSUE THREAD

**Issue by turgayacar** [sonvister/Binance#20]
Ihave this error try your wiki code copy and paste.
and I have this error my code.
I test your code but push this.

link on image screenshot.
[https://i.hizliresim.com/Vr2OWB.png](url)

thanks.

**Comment by raphaotten** [comment]
The API doesn't make sure, that a dot is used as decimal separator. This would be good to change. I had to switch my whole Application to english to get it working.

**Comment by turgayacar** [comment]
Thanks @raphaotten but nothing change.
Nothing changed. He continues to make mistakes in the same way.
I used the following code for english, but can you share if there is something different?

`Thread.CurrentThread.CurrentCulture = Thread.CurrentThread.CurrentUICulture = new CultureInfo("en-US");`

**Comment by raphaotten** [comment]
Yes, try 
`System.Globalization.CultureInfo.DefaultThreadCurrentCulture = new System.Globalization.CultureInfo("en-US");`
in the beginning of your application Form_Load, onInit or something like this.

Your command is only applied to the current thread, which is not enough.

**Comment by turgayacar** [comment]
Thank you very much for your interest. But it did not happen again.
My operating system is Windows 10 Enterprise X64 Turkish language.
I am developing on VS 2017 Enterprise.
I am developing a Windows Forms application.
I am using the Framework 4.7.1.
I get the same error even in the merit limit trade code indicated on the wiki pages.
Maybe I tried to give all the information that came to mind in the hope that I could get an error in a different way.
I hope I solve my problem as soon as possible.

**Comment by sonvister** [comment]
@raphaotten and @turgayacar, what version of the Binance library are you using? If you are using a version prior to 0.2.0-alpha.8, please upgrade to that or  a later version (refer to issue #8 for more information). If you are using that or a later version, I would like to know where else I need to modify the decimal to string conversion. Thanks.

**Comment by turgayacar** [comment]
Oh thanks.
im Updated 0.20 Alpha 11 
im ignored pre releases.
Best regards
