### ISSUE TITLE
LOT_SIZE errors and rounding

### ISSUE THREAD

**Issue by therealosman** [sonvister/Binance#23]
I'm sure I'm doing something wrong, but recently I can't place orders often because of the LOT_SIZE error. What's the ideal way to know how to round my quantity requests? This wasn't happening to me a few weeks ago, I'm not sure if Binance changed, my code or this API.

Any help is much appreciated!

**Comment by sonvister** [comment]
@therealosman the **/exchangeInfo** endpoint should tell you the current LOT_SIZE filter settings for a symbol. With that you can determine if the quantity you are requesting passes the [LOT_SIZE](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#lot_size) filter. Also, looking at the JSON of the request will tell you if this API is sending the quantity you expect.

**Comment by therealosman** [comment]
@sonvister Thanks! I can't find how to access the /exchangeinfo endpoint. Is there an API function for that in the library or am I missing something obvious? 

Cheers,
Oz

**Comment by sonvister** [comment]
You could use the low-level JSON API `IBinanceHttpClient.GetExchangeInfoAsync()` method, or look to the `Symbol.Quantity` property after calling `IBinanceApi.GetSymbolsAsync()`, or simply use a web browser:
https://api.binance.com/api/v1/exchangeInfo.

**Comment by therealosman** [comment]
@sonvister  Can't believe I missed the Symbol.Quantity thing, perhaps the naming threw me off. That fixes my problem, thank you!

**Comment by sonvister** [comment]
@therealosman, just wanted to make you aware of extensions for `Symbol.Quantity` and `Symbol.Price` recently added that convert amounts to valid increments. Perhaps you will find these useful. The extensions are: `GetUpperValidValue()`, `GetLowerValidValue()`, and `GetValidValue()`. See the method descriptions for details.
