### ISSUE TITLE
Which .net version to use?

### ISSUE THREAD

**Issue by tomastoth** [sonvister/Binance#25]
I have tried using both 2.0 and 4.7.1 but none of these seems to work and I always get the error which says that the package has no refference for my version of .net framework

**Comment by sonvister** [comment]
@tomastoth, the Binance library is compatible with **.NET Standard 2.0** and **.NET Framework 4.7.1**. I've created multiple sample applications you can reference using either. You'll have to be more specific about what you are doing otherwise I am *unable to reproduce*.

**Comment by sonvister** [comment]
Without additional information there is nothing I can do.
