### ISSUE TITLE
any plan to expand this to cover more exchanges?

### ISSUE THREAD

**Issue by wjchicago** [sonvister/Binance#27]
I have to admit this is the best crypto currency  exchange .Net API I have ever used. Do you have any plan to cover more exchanges?

**Comment by sonvister** [comment]
@wjchicago thanks!

I do plan to create other crypto exchange .NET API libraries like this one (*and share them*). Before this project, I had started on a **GDAX** .NET library. I will be working on it again after **Binance 0.2.0** is released/stable. Other exchanges that I've considered include: **Poloniex** and **Bittrex**.
