### ISSUE TITLE
The WebSocket protocol is not supported on this platform.

### ISSUE THREAD

**Issue by mirror222** [sonvister/Binance#3]
I got this message while running the BinanceMarketDepth project:

      DepthWebSocketClient.SubscribeToAsync       (exception: "The WebSocket protocol is not supported on this platform.")

any advice to fix this problem? thank you.

**Comment by sonvister** [comment]
What platform are you using (operating system and .NET version)?

**Comment by mirror222** [comment]
thanks for your prompt reply. I am running a Windows 7 64-bit with VS 2017.

**Comment by sonvister** [comment]
The implementation of `Binance.Api.WebSocket.IWebSocketClient` (`Binance.Api.WebSocket.WebSocketClient`) uses `System.Net.WebSocket.ClientWebSocket.`

MSDN:
"[Some of the classes and class elements in the System.Net.WebSockets namespace are supported on Windows 7, Windows Vista SP2, and Windows Server 2008. However, the only public implementations of client and server WebSockets are supported on Windows 8 and Windows Server 2012. The class elements in the System.Net.WebSockets namespace that are supported on Windows 7, Windows Vista SP2, and Windows Server 2008 are abstract class elements. This allows an application developer to inherit and extend these abstract class classes and class elements with an actual implementation of client WebSockets.](https://msdn.microsoft.com/en-us/library/system.net.websockets.clientwebsocket(v=vs.110).aspx)"

*Basically, it is not supported on your platform.*

Options:
1. In VS 2017, in the Binance library NuGet packages, install the latest `System.Net.WebSockets.Client` package ([v4.3.2](https://www.nuget.org/packages/System.Net.WebSockets.Client)) to see if any updates add support for Win7 (*I have no reason to believe it will support Win7, but I would like to try and find out*).

2. Use an alternative WebSocket implementation library such as [WebSocket4Net](https://github.com/kerryjiang/WebSocket4Net) or [WebSocket-Sharp](https://github.com/sta/websocket-sharp) and create a new `Binance.Api.WebSocket.IWebSocketClient` implementation adapting to the other WebSocket library. Then configure DI to use that implementation instead: `services.AddTransient<IWebSocketClient, YourWebSocketClient>();` after calling `AddBinance()`. This should be able to be done at the application level and not require you to modify the Binance library.

**Comment by mirror222** [comment]
awesome!  Thank you so much, I'll do same tests myself.

**Comment by wjchicago** [comment]
@sonvister This issue bothers me as well. I can confirm your first suggestion will not kill the problem.

I tried to follow your suggestion (2) to implement a WebSocket4Net or WebSocket-Sharp version, actually I did for both. However none of them works for me. 

May I ask you to take a look and if you can spot any obvious mistake? I am running out of idea now.
You can find them [here](https://github.com/wjchicago/sparklo)

**Comment by sonvister** [comment]
@mirror222 and @wjchicago, I created implementations (*in separate libraries*) for both WebSocket4Net and WebSocket-Sharp. The usage is shown (*in comments*) in `BinanceConsoleApp`.

**Comment by mirror222** [comment]
Thank you for keeping me informed and your professional help.

**Comment by wjchicago** [comment]
@sonvister Thank you for your effort to make the project better and better!
