### ISSUE TITLE
Multiple Orderbook Cache

### ISSUE THREAD

**Issue by wjchicago** [sonvister/Binance#30]
Due to the dependency injection, it looks like OrderBookCache has to be a singleton. It is not possible to have two or more OrderBookCaches in one instance. 

I tried to listen to two orderbooks but seems the later will overwrite the websocket streaming of the first one. Just tried with "BTCUSDT" and "ETHUSDT" and I got:

OrderBookCache is already linked to this DepthWebSocketClient.
info: Binance.Api.WebSocket.BinanceWebSocketStream[0]
      BinanceWebSocketStream.StreamAsync: "wss://stream.binance.com:9443/ws/ethbtc@depth20"

@sonvister can you please confirm my understanding?

**Comment by wjchicago** [comment]
Sorry I made a mistake.  You code works perfectly.

**Comment by sonvister** [comment]
@wjchicago, I'll assume you hadn't gotten to the the latest version yet (*if so we can share that mistake*). 🤦‍♂️

**Comment by sonvister** [comment]
@wjchicago, I created `MultiCacheExample` and `MultiCacheExampleCombinedStreams` in `BinanceMarketDepth` sample application to demonstrate (*and confirm*) usage and behavior using either multiple controllers and web sockets or a single controller with a combined web socket stream.
