### ISSUE TITLE
SymbolStatisticsCache subscription without using a symbol

### ISSUE THREAD

**Issue by muskara** [sonvister/Binance#34]
https://github.com/sonvister/Binance/blob/7ad8457e505ecc138e456a1f120570288260760c/src/Binance/Cache/SymbolStatisticsCache.cs#L143

This is pointless when subscribe without using a symbol (**!ticker@arr** parameter)

**Comment by sonvister** [comment]
Thanks 🤦‍♂️

**Comment by sonvister** [comment]
I meant to close #46 with that commit.
