### ISSUE TITLE
Commission throw exception

### ISSUE THREAD

**Issue by dohieu1991** [sonvister/Binance#36]
It looks like the commission returns from the api of binance as the quantity rather than the percent. Please confirm the issue and fix in the next release.

**Comment by sonvister** [comment]
Thanks @dohieu1991. When I created that class I thought the values were % (*no documentation*) and didn't think about that exception again even though the numbers I had seen didn't make sense... 🤦‍♂️ Now I know they represent [basis points](https://www.investopedia.com/terms/b/basispoint.asp) (bips) based on the user data stream [documentation](https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md).

**Comment by sonvister** [comment]
However, the values still don't make complete sense... I see commission values of 10 (0.1%) in my account info data even though I am using BNB for fees... I would expect to see 5 (0.05%) instead.

**Comment by dohieu1991** [comment]
Dear sonvister,
Please see the pictures and you can see what I mean.
First, this is the method I used:
[image: Hình ảnh nội tuyến 4]
Second, An exception raised
[image: Hình ảnh nội tuyến 5]
Then I try used response string before deserialize it:
[image: Hình ảnh nội tuyến 6]
And here is complete detail of an trade:
[image: Hình ảnh nội tuyến 7]

Thanks and best regards,
HieuDo

2018-01-27 0:26 GMT+07:00 sonvister <notifications@github.com>:

**Comment by dohieu1991** [comment]
![method](https://user-images.githubusercontent.com/16361425/35453690-b823292a-02fd-11e8-8399-f2180963493c.PNG)
![exception](https://user-images.githubusercontent.com/16361425/35453693-bbd4ac1a-02fd-11e8-9a7d-87d6479c20c9.PNG)
![many trades has commission larger than 100](https://user-images.githubusercontent.com/16361425/35453701-c00ee05c-02fd-11e8-9d6d-bc4545b80698.PNG)
![commission larger than 100](https://user-images.githubusercontent.com/16361425/35453704-c20d5910-02fd-11e8-86b2-a5d3b9876fac.PNG)

Please reopen this issue. Thanks

**Comment by sonvister** [comment]
@dohieu1991, that's kinda funny... you helped fix a completely different issue. I'll look at what you have here, now that I see what is throwing and what is being thrown.

**Comment by sonvister** [comment]
@dohieu1991, got it. I'll remove the argument check and exception in `AccountTrade` (`Fill` doesn't have that commission argument check).

**Comment by sonvister** [comment]
@dohieu1991 thanks for the clarification of the issue... please let me know if **0.2.0-alpha21** has any issues... have FUN 😁 (*pun intended*).
