### ISSUE TITLE
Alpha 21 is so Hard :(

### ISSUE THREAD

**Issue by turgayacar** [sonvister/Binance#37]
Greetings;

Thanks for the new update. But the datetime surprise in the new update surprised me a lot. it was really difficult to make the project mistakes. TimeStamp was actually able to solve the transformation very easily on the user side. At least I did not encounter this problem at all. Well, whatever the developer knows, it's the best thing. Thank you.
It will be my proposal. A development for chart data is not bad. For example, it would be very helpful if there was a method to handle the indicator data.
SMA, TEMA, EMA, RSI, MACD indicators will add a truly unrivaled library. Even if it succeeds, it will be very good and far ahead of all the stock market libraries. Because it is really difficult to create these indicators and equalize and process the data, and on our behalf this information will not be as stable and fast as yours.
I wish you good work.
Best regards...

**Comment by sonvister** [comment]
@turgayacar I try to accommodate everyone best I can, but that is a futile effort. As alpha or even in 0.x versions, you should be prepared for anything and I try to highlight breaking changes in the release notes to avoid "surprises". In the end, decisions come down to what I consider to be best for the project at the time ...maybe not always best for everyone especially existing users like yourself. I considered this change from `long` to `DateTime` might be unwelcome or as tedious a change for others as it was for me. But it seemed to make sense to convert to a more familiar, strongly typed, time representation as requested on `Candlestick` and to be consistent with other time properties in other classes. Ugh, yes. But, I did provide an extension `ToTimestamp()` for, hopefully easy, backward compatibility if you want Unix time milliseconds instead.

**Comment by sonvister** [comment]
@turgayacar the additional data processing will come in time (*when I actually get to using this library in my own projects*), but it will certainly be in a different, higher-level, library that will work with multiple exchange API libraries such as this one. I have mentioned to others that I will be working on other exchange APIs beginning with GDAX once I get this to 0.2.0 and stop surprising you with new features and breaking changes 😉

**Comment by sonvister** [comment]
Also, for those of you using `JsonConvert.SerializeObject()` and `JsonConvert.DeserializeObject()`, I added `TimestampJsonConverter` class to convert `DateTime` to `long` and back again.
