### ISSUE TITLE
Streams mysteriously stopped

### ISSUE THREAD

**Issue by pingu2k4** [sonvister/Binance#39]
Hey, making a project using this (Thanks btw!) and have run it for 18+ hours several times (before finding a bug in my own logic and restarting after making the fix).
I restarted last night at around 2am, for this reason. I left it run overnight whilst I went to be. When I came back to it, the 2 streams I had setup had stopped.
I started off an OrderBook stream for BTC_USDT, and another for AccountInfo. The last orderbook update was at just past 6am, (but I was looking at it at gone 7am). Also during that time a trade had filled, but the program had not been notified of this (as it hadn't updated to show that like it should have done).

Unfortuntely, I turned off the main logging, as it was messing up the appearance of my console. Ive turned it back on now, but not added it to console so it only goes to file. 

Not sure why this may have happened, perhaps my internet dropped for a period of time? What would be best for me to do, have something that checks to see how long ago the most recent update was, and if its out of date then try and reconnect somehow? Is there any event fired or something when streams are stopped for any reason other than I asked them to?

**Comment by pingu2k4** [comment]
Happened again today. Caught the error in the logs this time: [fail] 29/01/2018 16:56:01 +00:00
      DefaultWebSocketClient.StreamAsync: WebSocket receive exception.
      (exception: "The connection with the server was terminated abnormally")
[fail] 29/01/2018 16:56:01 +00:00
      DefaultWebSocketClient.StreamAsync: WebSocket close exception.
      (exception: "The connection with the server was terminated abnormally")
[fail] 29/01/2018 16:56:01 +00:00
      BinanceWebSocketStream.StreamAsync
      (exception: "The connection with the server was terminated abnormally")
[fail] 29/01/2018 16:56:01 +00:00
      DefaultWebSocketClient.StreamAsync: WebSocket receive exception.
      (exception: "The connection with the server was terminated abnormally")
[fail] 29/01/2018 16:56:01 +00:00
      DefaultWebSocketClient.StreamAsync: WebSocket close exception.
      (exception: "The connection with the server was terminated abnormally")
[fail] 29/01/2018 16:56:01 +00:00
      BinanceWebSocketStream.StreamAsync
      (exception: "The connection with the server was terminated abnormally")

How would I catch this and restart the streams? :S

**Comment by sonvister** [comment]
@pingu2k4, so far this looks normal assuming you have a couple of `BinanceWebSocketStreams` active. I see you are not using the latest version, which has additional logging information (*I recommend upgrading for that reason alone*). Regardless, after the exception is logged in `BinanceWebSocketStream`, it is thrown to the caller to handle. If you want to catch it just add try/catch. In the sample applications I use `RetryTaskController`, which forwards the exception to an error handler (*to display on screen*), waits a bit, and calls `StreamAsync` again to reconnect. If you could provide logger output from the latest version as well as some additional context (*from log and application*) that will help me if you are still having issues.

**Comment by pingu2k4** [comment]
Thanks for the response. Having a little trouble understanding exactly what I should be doing though.

Ive updated to alpha22. I have been looking at some of the recent commits, and I think this may work?

Currently, I have the following:

`                OrderBookCache = Program.ServiceProvider.GetService<IOrderBookCache>();
                OrderBookCache.Update += OnOrderBookUpdated;

                Ticker = Task.Run(() =>
                {
                    OrderBookCache.StreamAsync(Program.SYMBOL, 20, TokenSource.Token);
                }, TokenSource.Token);`

It appears that if I add the following:

`                OrderBookCache = Program.ServiceProvider.GetService<IOrderBookCache>();
                OrderBookCache.Update += OnOrderBookUpdated;
                OrderBookCache.Client.WebSocket.Client.Close += OnClose;

                Ticker = Task.Run(() =>
                {
                    OrderBookCache.StreamAsync(Program.SYMBOL, 20, TokenSource.Token);
                }, TokenSource.Token);`

that I could just have it catch the close event, and then in the OnClose event I could have it just try and open it again? 

I did take a look at the samples using the RetryTaskController, reason I hadnt seen that before was I was working just from looking at the Console sample until now. I couldn't really translate what I saw of the RetryTaskController into what I should be doing with it, sorry. :( 

I am opening 2 streams, one for the orderbook of one symbol, and one for the UserData.

**Comment by pingu2k4** [comment]
To add to the above - I looked more into it, and I don't have SubscribeAndStreamAsync in Binance.Cache. Using Nuget, and im on alpha 22.

**Comment by sonvister** [comment]
@pingu2k4 if you have 0.2.0-alpha22, that *is* the latest and there is nothing to do in that regard. Often I will push code that hasn't been released for anyone wanting to build and test ahead of my releases or review code, etc. The `SubscribeAndStreamAsync` method will be in 0.2.0-alpha23. If you are wanting to view code for a particular release you will want to select the appropriate Tag.

The `StreamAsync` method returns a `Task`, if you are only calling that method you do not need to wrap it with another `Task`. You could use the `Close` event in that way since it is raised before the `Task` completes, but only if the connection was opened (*won't occur if connection fails*). So, I still recommend using try/catch to handle exceptions. If you are not interested in the exception, just call `StreamAsync` again when the `Task` completes. `RetryTaskController` is basically just a `Task` encapsulating a continuous loop.
