### ISSUE TITLE
ETCBTC causing failure in GetSymbolsAsync method

### ISSUE THREAD

**Issue by attilah** [sonvister/Binance#4]
From the API ETCBTC's symbol name is 'ETC' which fails the symbol name comparison within the ```GetSymbolsAsync``` method.

I think instead of this logic:
```
if (symbol.ToString() != jToken["symbol"].Value<string>())
{
    throw new BinanceApiException($"Symbol does not match assets ({jToken["symbol"].Value<string>()} != {symbol}).");
}
```

Taking just the symbol's name and use it would be a better solution.

**Comment by sonvister** [comment]
'ETC' is not a valid symbol. I have changed GetSymbolsAsync to log and ignore rather that throw exception on invalid symbols.
