### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by vergilbg** [sonvister/Binance#44]
I get the following exception:
Could not load file or assembly 'Microsoft.Extensions.Options, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

I am truing to do the simplest test. Build fine, but throws exception on run-time.

Code:

`class Program
    {
        static void Main(string[] args)
        {
            var a = new BinanceApi();
        }
    }`

**Comment by sonvister** [comment]
@vergilbg, that assembly is one of the required [NuGet](https://www.nuget.org/packages/Binance/0.2.0-alpha24) dependencies.

[Dependencies](https://www.nuget.org/packages/Binance/0.2.0-alpha24):

Microsoft.Extensions.DependencyInjection.Abstractions (>= 2.0.0)
Microsoft.Extensions.Logging.Abstractions (>= 2.0.0)
Microsoft.Extensions.Options (>= 2.0.0)
Newtonsoft.Json (>= 10.0.3)
System.Threading.Tasks.Dataflow (>= 4.8.0)
System.Threading.Tasks.Extensions (>= 4.4.0)
