### ISSUE TITLE
SingleUserDataWebSocketClient: throw when OnKeepAliveTimer raises error

### ISSUE THREAD

**Issue by rakewell** [sonvister/Binance#45]
Hello,

SingleUserDataWebSocketClient

Would it be ok to propagate the error when its raised in the OnKeepAliveTimer function? 

```
        /// <summary>
        /// Keep-alive timer callback.
        /// </summary>
        /// <param name="state"></param>
        private async void OnKeepAliveTimer(object state)
        {
            try
            {
                Logger?.LogDebug($"{nameof(SingleUserDataWebSocketClient)}.{nameof(OnKeepAliveTimer)}: User stream keep alive (\"{_listenKey}\").  [thread: {Thread.CurrentThread.ManagedThreadId}]");

                await _api.UserStreamKeepAliveAsync(User, _listenKey, (CancellationToken)state)
                    .ConfigureAwait(false);
            }
            catch (Exception e)
            {
                Logger?.LogError(e, $"{nameof(SingleUserDataWebSocketClient)}.{nameof(OnKeepAliveTimer)}: Failed to ping user data stream.");
            }
        }
```

Whilst I was testing the keep alive failed for some reason and I stopped getting user updates. I did see the errors in the log however. It would be good if the error was propagated. I also failed to get a notification that the socket was closed. I would imagine that if the keep alive token issn't issued then it would close eventually but for some reason my event didn't fire.

**Comment by sonvister** [comment]
@rakewell can you provide the log?

**Comment by rakewell** [comment]
[warn] 31/01/2018 5:44:11 PM +11:00
       UserDataWebSocketClient.OnKeepAliveTimer: "[InternalServerError]: 'Server Error' - An unknown error occured while processing the request. (-1000)"
      (exception: [InternalServerError]: 'Server Error' - An unknown error occured while processing the request. (-1000))

**Comment by sonvister** [comment]
@rakewell it looks like you are not using **0.2.0-alpha24** based on that warning message. Please upgrade to the latest version.

**Comment by rakewell** [comment]
I think you are correct, at the time the log was taken I was using alpha22. Now i'm on alpha24. The code snippet  I sent from alpha24 does seem to show that the exception is handled by the logger only and is not propagated. Is this by design?
