### ISSUE TITLE
Failing to parse JSON for GetDepositAddress

### ISSUE THREAD

**Issue by pingu2k4** [sonvister/Binance#46]
Was getting deposit address for BTC, and I see this error:

Binance.Api.BinanceApiException: 'BinanceApi.GetDepositAddressAsync failed to parse JSON api response: "{"address":"blah","success":true,"addressTag":"","url":"https://btc.com/[Ljava.lang.String;@4ea6f448"}"'

ArgumentNullException: Value cannot be null.

I don't use it, but I'm implementing and testing all features you have implemented in your wrapper, and came across this. No rush, for me anyway, I dont need this.

**Comment by sonvister** [comment]
@pingu2k4, thanks for mentioning. It looks like that response is missing 'asset', which causes the exception. I'll update the code to not rely on the response having asset. Also, the 'url' is new, but I won't add support for it unless it is added to the official docs.

**Comment by sonvister** [comment]
Meant to close this with commit: 60fa1716973c615a459d6e307d796d0715b32bef.
