### ISSUE TITLE
Exception when PlaceLimitOrder

### ISSUE THREAD

**Issue by YLPeng** [sonvister/Binance#49]
I apologize if I did sth foolish, but I keep getting System.AggregateException: 'One or more errors occurred. (Object reference not set to an instance of an object.)' when I try to place limit order. (both TestPlaceOrder and real)
The inner exception stack trace is : 
   at Binance.Api.BinanceHttpClientExtensions.<PlaceOrderAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.Api.BinanceApi.<TestPlaceAsync>d__34.MoveNext()

I am using version 0.2.0-alpha27, please help!

Thanks.

**Comment by YLPeng** [comment]
After trying a few things, I was able to place order when I downgrade the version to v0.2.0-alpha24.

Therefore, potentially, the issue was introduced since alpha 25.

**Comment by sonvister** [comment]
@YLPeng, thanks for mentioning this. I see a potential problem that was introduced with 0.2.0-alpha25. If you are not using dependency injection (or `IBinanceApiUserProvider`) or creating an `IApiRateLimiter` when creating `IBinanceApiUser` the associated 'order' rate limiter is null. The changes with 0.2.0-alpha25 failed to check for that case.

So, assuming that's the case, just feed a `new ApiRateLimiter()` to `new BinanceApiUser(rateLimiter: <the rate limiter>)` and that should work.

**Comment by sonvister** [comment]
@YLPeng, let me know if changes made to **0.2.0-alpha28** solves this issue. Thanks.

**Comment by YLPeng** [comment]
@sonvister verified the bug has been fixed:) THanks!
