### ISSUE TITLE
candlestick start and end dates - what is the time zone?

### ISSUE THREAD

**Issue by pavlexander** [sonvister/Binance#51]
Short question - what is the datetime zone for candlesticks? I was thinking that it's in UTC, however, after calling the API a couple of times - I am feeling lost.

At the moment of writing current UTC time is: **2/8/2018 12:06:11 PM**
Latest candle close dateime from API is: **2/8/2018 12:28:14 AM**
Which is 12 hours difference.

This does not make any sense. It feels like that new candles are either added by binance with some delay, or candle timezone is -12 (average?? not exact) hours from UTC.

Therefore following clarifications are necessary:
1. What is the datetime zone for candles (_open_/_close_ DT) returned from API? Is it in UTC?
2. How often does binance update/add new candles? Is there such info?

P.s. in my tests I was using 5 minute interval.

Thanks in advance,
Aleksandrs

**Comment by sonvister** [comment]
@pavlexander, all `DateTime` properties are **UTC**.

From [Binance Official Documentation](https://github.com/binance-exchange/binance-official-api-docs): "all time and timestamp related fields are in [Unix time] milliseconds."

This library converts all timestamps to `DateTime` using:
```C#
DateTimeOffset.FromUnixTimeMilliseconds(timestamp).UtcDateTime;
```
*NOTE: If you want to convert `DateTime` **UTC** to timestamp you can use the `ToTimestamp()` extension.*

If you find that data received from the Binance REST API is in error, then that issue would be more appropriately directed to the [Binance Official API Telegram](https://t.me/binance_api_english).

To bypass this library, you can use your web browser (*or Postman*):\
[https://api.binance.com/api/v1/klines?symbol=BTCUSDT&interval=5m&limit=10](https://api.binance.com/api/v1/klines?symbol=BTCUSDT&interval=5m&limit=10)

If you find that this library is misrepresenting data, please let me know.

**Comment by sonvister** [comment]
@pavlexander, keep in mind they are currently undergoing [*unscheduled*] [system maintenance](https://twitter.com/binance_2017/status/961397899241254914).

**Comment by sonvister** [comment]
@pavlexander, is this resolved (*can this be closed*)?

**Comment by pavlexander** [comment]
Yes, closing. I have opened tickets on Binance itself.
