### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by sanchoflat** [sonvister/Binance#53]
Hi, is it possible to contact with you? Maybe email? Or you can write me on sanchoflat@Gmail.com

**Comment by sonvister** [comment]
@sanchoflat, feel free to send me a direct message on [Twitter](https://twitter.com/sonvister).

**Comment by sonvister** [comment]
@sanchoflat, now direct messages should work. Sorry, if you tried already, the Twitter 'error' banner is the same color (blue) as 'successful' when changing profile settings and I didn't notice that I put in the wrong password before.

Let me know if this doesn't work for you.
