### ISSUE TITLE
Change subdomain?

### ISSUE THREAD

**Issue by pingu2k4** [sonvister/Binance#55]
Currently, www.binance.com isnt resolving for me, as per their ongoing issues.

I can load us.binance.com as directed from their twitter etc, but cannot connect using this API wrapper as it uses www. Is there any way to change it to us temporarily? IF not, could be a useful feature for the future. Perhaps something in appsettings.json or the endpoint to use?

(Actually, im not 100% sure the API is accessible from the us subdomain, though I would assume it is...)

For anyone else, I havent tried it yet but I am assuming a temporary fix would be to setup a hosts file entry redirecting www traffic to us traffic on binance domain, by getting the IP by pinging us.binance.com...

**Comment by sonvister** [comment]
@pingu2k4, I recommend you upgrade to **0.2.0-alpha30**. This issue should be resolved as of [0.2.0-alpha29](https://github.com/sonvister/Binance/releases/tag/v0.2.0-alpha29).

**Comment by pingu2k4** [comment]
Thats sorted it now, thanks. Was a lot of work changing from alpha24 to alpha30! (mainly websockets)
