### ISSUE TITLE
alpha30: No longer getting events handled - SingleUserDataWebSocketClient

### ISSUE THREAD

**Issue by rakewell** [sonvister/Binance#56]
Hello,

The following event handlers are not firing for SingleUserDataWebSocketClient: 
OrderUpdate
TradeUpdate
AcocuntUpdate

The Close and Open event handlers are firing. 

I suspect it's not a bug but the problem with the way i am subscribing to  the stream. I don't know what to put as the listen key. I have tried my ApiKey and any random text but I am not getting the events called.

```
        m_BinanceUserSocket = New SingleUserDataWebSocketClient(New WebSocketStreamProvider, UserDataSocketLogger)
            m_BinanceUserSocket.Subscribe(<what to put as listen key?>, m_BinanceUser)
            Dim streamTask = m_BinanceUserSocket.WebSocket.StreamAsync(Me.m_BinanceUserSocketCancel.Token)
            streamTask.ContinueWith(Sub(t As Task)
                                        If t.IsFaulted Then
                                            Me.Invoke(Sub() Me.HandleSocketApiException(t.Exception))
                                        End If
                                    End Sub)
```

Thanks in advance for your help.

**Comment by sonvister** [comment]
@rakewell, is this this issue?

0.2.0-alpha25 Changes:
- *BREAKING*: Change `IUserDataWebSocketClient` to `IUserDataWebSocketManager`.
  - New `IUserDataWebSocketClient` handles only low-level subscribe/unsubscribe of listen keys.

If so, you will want to use `UserDataWebSocketManager` instead. It manages the listen keys, client, and keep-alive timer.

**Comment by rakewell** [comment]
@sonvister yes, that's the one. Just in case other's need the solution:
```

        Me.m_BinanceUserSocketClient = New SingleUserDataWebSocketClient(New WebSocketStreamProvider, UserDataSocketLogger)
        Dim alive = New UserDataKeepAliveTimerProvider()
        m_BinanceUserSocket = New UserDataWebSocketManager(Me.m_BinanceApi, m_BinanceUserSocketClient, alive,, UserDataSocketLogger)

        AddHandler Me.m_BinanceUserSocketClient.Close, AddressOf Me.m_BinanceUserSocket_Close
```
If you want to get Open and Close event handlers you still need to use the SingleUserDataWebSocketClient object, is that correct. Also can the keepAliveTimerProvider be optional?

**Comment by sonvister** [comment]
@rakewell, can this be closed?
