### ISSUE TITLE
Can't seem to find the UserDataWebSocketClient Message event in alpha30

### ISSUE THREAD

**Issue by rakewell** [sonvister/Binance#57]
I was able to capture raw websocket messages on the message event of the SingleUserDataWebSocketClient. I thought it might be available in the new UserDataWebSocketManager but it doesn't seem to be there either. It might be nice to have all the events in one class (Open, Close, Message - from the SingleUserDataWebSocketClient, and AccountUpdate, OrderUpdate and TradeUpdate now on the UserDataWebScoketManager. The Manager class seems to be the right place.

**Comment by sonvister** [comment]
@rakewell, in 0.2.0-alpha35 any class that is an `IJsonProvider` or has an `IJsonProvider` allows for the capturing of `raw` JSON data using the `Message` event. Please see [0.2.0-alpha35 release documentation](https://github.com/sonvister/Binance/releases/tag/v0.2.0-alpha35) for additional information.

**Comment by rakewell** [comment]
many thanks @sonvister, the message handler now works great in alpha35.
