### ISSUE TITLE
Websocket example or tutorial 

### ISSUE THREAD

**Issue by YLPeng** [sonvister/Binance#58]
Hi Sonvister,

I'm trying to implement screaming features in my app. Is there any examples or documents that I can borrow? 

I started somthing like: 

`        void CreateCandlesticksCache(Symbol symbol)
        {
            var conf = new CandlestickWebSocketClient(new BinanceWebSocketStream());
            var ca = new CandlestickCache(Api, conf);
        }`

Not sure if this is the correct direction to go. 

Thanks in advance!

**Comment by sonvister** [comment]
@YLPeng, there are many examples of 😱 features in the sample applications.

**Comment by YLPeng** [comment]
Ok I will dig through it. Thanks
