### ISSUE TITLE
exception: BinanceWebSocketStream.Subscribe: Subscribing (a stream) must be done when not streaming.

### ISSUE THREAD

**Issue by rakewell** [sonvister/Binance#61]
I am sometimes getting an exception when Unsubscribing and then resubscribing to the AggregateTradeWebSocketClient streams. I need to do this when an additional subscription is needed for streaming. Here is the code:

-- UNSUBSCRIBE

```
    Private Sub UnSubscibeAllTradeUpdatesManaged()
        Dim msg As String

        If Me.m_BinanceAggregateTradeSocketCancel IsNot Nothing Then
            msg = "Un-Subscribing all tickers before ticker registration takes place.."
            Me.UpdateMessageList(msg)


            Me.m_BinanceAggregateTradeSocketCancel.Cancel() 'this will cancel all streams 
            Me.m_BinanceAggregateTradeSocketCancel.Dispose()
            Me.m_BinanceAggregateTradeSocketCancel = Nothing
        End If
    End Sub

```

--SUBSCRIBE

```

Private Async Sub SubscibeAllTradeUpdates()

        Dim msg As String

        'one thread at a time
        Await m_SubscriptionThreadLimiter.WaitAsync()

        'we don't want the close event firing another connection attempt in the middle of subscirptions
        RemoveHandler m_BinanceTradeSocketStreamClient.Close, AddressOf Me.m_BinanceSocketTradeStreamClient_Close

        Try

            Me.UnSubscibeAllTradeUpdatesManaged()

            'we can now register the events cause we have a unique set of symbols
            Me.m_BinanceAggregateTradeSocketCancel = New CancellationTokenSource

            'we need to stream at least one asset to deterine if the stream was successful 
            If Not m_AssetsRequiredForTickerUpdates.ContainsKey(Binance.Symbol.BTC_USDT.ToString) Then
                m_AssetsRequiredForTickerUpdates.Add(Binance.Symbol.BTC_USDT.ToString, 0)
            End If

            For Each assRow In Me.m_AssetsRequiredForTickerUpdates
                msg = "Subscribing to " & assRow.Key
                Me.UpdateMessageList(msg)
                Me.m_BinanceAggregateTradeSocket.Subscribe(assRow.Key)
            Next

            'this actually starts the streaming, all assets must be subscribed first
  Me.m_BinanceAggregateTradeSocket.StreamAsync(m_BinanceAggregateTradeSocketCancel.Token)

        Catch ex As Exception
            Throw ex
        Finally
            AddHandler m_BinanceTradeSocketStreamClient.Close, AddressOf Me.m_BinanceSocketTradeStreamClient_Close
            m_SubscriptionThreadLimiter.Release()
        End Try
    End Sub

```
As you can see, when subscribing is called, it always cancels the current stream by using the cancellation token.

I have also included the m_SubscriptionThreadLimiter which is a Semaphore object that is used to limit the execution of the sub procedure to one thread:
` Private m_SubscriptionThreadLimiter As SemaphoreSlim = New SemaphoreSlim(1, 1)`

Sometimes I get an exception raised below and my initial thought was that I needed to Await the StreamAsync function so that the m_SubscriptionThreadLimiter doesn't release prematurely. If I do so however the StreamAsync doesn't return (this is probably by design as the streaming is ongoing). Other than that, I can't think of another reason I am getting the 'Subscribing (a stream) must be done when not streaming.' error. Do you have any thoughts?

Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Binance.dll
Exception thrown: 'System.InvalidOperationException' in MessStockBot.exe
An exception of type 'System.InvalidOperationException' occurred in Bot.exe but was not handled in user code
BinanceWebSocketStream.Subscribe: Subscribing (a stream) must be done when not streaming.

**Comment by rakewell** [comment]
it seems that adding `Me.m_BinanceAggregateTradeSocket.UnsubscribeAll()` to the unsubscription function resolved the issue.

**Comment by rakewell** [comment]
I am now getting an exception when UnSubscribing even though I am Cancelling the token first:

"BinanceWebSocketStream.Unsubscribe: Unsubscribing (a stream) must be done when not streaming."

**Comment by rakewell** [comment]
adding Thread.Sleep(1000) before the UnSubscibeAll seems to fix the problem:
```

            Me.m_BinanceAggregateTradeSocketCancel.Cancel() 'this will cancel all streams 

            Me.m_BinanceAggregateTradeSocketCancel.Dispose()
            Me.m_BinanceAggregateTradeSocketCancel = Nothing

            Thread.Sleep(1000)
            Me.m_BinanceAggregateTradeSocket.UnsubscribeAll()
```
There must be some delay in the cancellation of the stream so it is still running when UnSubscribleAll is Called straight after.

**Comment by sonvister** [comment]
@rakewell, do you have any more to add (*can this be closed*)?

**Comment by rakewell** [comment]
nothing more to add, please go ahead and cancel.
