### ISSUE TITLE
Subscribing to multiple similar streams too fast causes error

### ISSUE THREAD

**Issue by pingu2k4** [sonvister/Binance#62]
Hey,

Maybe I'm doing something wrong, but here's what I have:

`            await MarketData.LiveOrderBook(Config.settings.GetSymbol1, command: OnOrderBookUpdated, token: cancellationTokenSource.Token);
            await MarketData.LiveOrderBook(Config.settings.GetSymbol2, command: OnOrderBookUpdated, token: cancellationTokenSource.Token);
            await MarketData.LiveOrderBook(Config.settings.GetSymbol3, command: OnOrderBookUpdated, token: cancellationTokenSource.Token);
            await MarketData.LiveOrderBook(Config.settings.GetSymbol4, command: OnOrderBookUpdated, token: cancellationTokenSource.Token);`

And the method that is calling does the following:

`        public static async Task<bool> LiveOrderBook(string symbol, int depth = 20, Action<DepthUpdateEventArgs> command = null, CancellationToken token = default)
        {
            Writer.WriteBuffer("Starting Live OrderBook Feed...", symbol, ConsoleColor.Gray, Logger.LogLevel.INFO);

            Program.clientManager.DepthClient.Subscribe(symbol, depth, command);

            await ((IBinanceWebSocketClientAdapter)Program.clientManager.DepthClient).Task;

            return true;
        }`

However when I run this, I get the following in the log:
[dbug] 15/02/2018 23:57:20 +00:00
      DepthWebSocketClientAdapter.Subscribe: Cancel streaming...  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      DepthWebSocketClient.Subscribe: "BTCUSDT" "20" (callback: yes).  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketClient.SubscribeStream: Adding stream ("btcusdt@depth20").  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.Subscribe: "btcusdt@depth20" (callback: yes).  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.Subscribe: Adding stream: "btcusdt@depth20"  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.Subscribe: Adding callback for stream: "btcusdt@depth20"  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketClient.SubscribeStream: Adding callback for stream ("btcusdt@depth20").  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      DepthWebSocketClientAdapter.Subscribe: Begin streaming...  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      DepthWebSocketClientAdapter.Subscribe: Cancel streaming...  [thread: 6]
[dbug] 15/02/2018 23:57:20 +00:00
      DepthWebSocketClient.Subscribe: "LTCUSDT" "20" (callback: yes).  [thread: 12]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketClient.SubscribeStream: Adding stream ("ltcusdt@depth20").  [thread: 12]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.Subscribe: "ltcusdt@depth20" (callback: yes).  [thread: 12]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.Subscribe: Adding stream: "ltcusdt@depth20"  [thread: 12]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.Subscribe: Adding callback for stream: "ltcusdt@depth20"  [thread: 12]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketClient.SubscribeStream: Adding callback for stream ("ltcusdt@depth20").  [thread: 12]
[dbug] 15/02/2018 23:57:20 +00:00
      DepthWebSocketClientAdapter.Subscribe: Begin streaming...  [thread: 12]
[info] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.StreamAsync: "wss://stream.binance.com:9443/stream?streams=btcusdt@depth20/ltcusdt@depth20"
[dbug] 15/02/2018 23:57:20 +00:00
      DepthWebSocketClientAdapter.Subscribe: Cancel streaming...  [thread: 7]
[dbug] 15/02/2018 23:57:20 +00:00
      DepthWebSocketClientAdapter.Subscribe: Cancel streaming...  [thread: 14]
[dbug] 15/02/2018 23:57:20 +00:00
      DepthWebSocketClient.Subscribe: "BNBUSDT" "20" (callback: yes).  [thread: 14]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketClient.SubscribeStream: Adding stream ("bnbusdt@depth20").  [thread: 14]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.Subscribe: "bnbusdt@depth20" (callback: yes).  [thread: 14]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.Subscribe: Adding stream: "bnbusdt@depth20"  [thread: 14]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.Subscribe: Adding callback for stream: "bnbusdt@depth20"  [thread: 14]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketClient.SubscribeStream: Adding callback for stream ("bnbusdt@depth20").  [thread: 14]
[dbug] 15/02/2018 23:57:20 +00:00
      DepthWebSocketClientAdapter.Subscribe: Begin streaming...  [thread: 14]
[info] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.StreamAsync: "wss://stream.binance.com:9443/stream?streams=btcusdt@depth20/ltcusdt@depth20/bnbusdt@depth20"
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.StreamAsync: Task complete.  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceHttpClient: "{"listenKey":"kAisw7JrMW5okOtcRH4xOW4FtIY26qc1poydOFVBCdLQUNktfSqQcXuj89Fi"}"
[dbug] 15/02/2018 23:57:20 +00:00
      UserDataWebSocketManager.SubscribeAndStreamAsync: User stream open ("kAisw7JrMW5okOtcRH4xOW4FtIY26qc1poydOFVBCdLQUNktfSqQcXuj89Fi").  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      UserDataWebSocketClient.Subscribe: "kAisw7JrMW5okOtcRH4xOW4FtIY26qc1poydOFVBCdLQUNktfSqQcXuj89Fi" (callback: no).  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketClient.SubscribeStream: Adding stream ("kAisw7JrMW5okOtcRH4xOW4FtIY26qc1poydOFVBCdLQUNktfSqQcXuj89Fi").  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.Subscribe: "kAisw7JrMW5okOtcRH4xOW4FtIY26qc1poydOFVBCdLQUNktfSqQcXuj89Fi" (callback: yes).  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.Subscribe: Adding stream: "kAisw7JrMW5okOtcRH4xOW4FtIY26qc1poydOFVBCdLQUNktfSqQcXuj89Fi"  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.Subscribe: Adding callback for stream: "kAisw7JrMW5okOtcRH4xOW4FtIY26qc1poydOFVBCdLQUNktfSqQcXuj89Fi"  [thread: 5]
[dbug] 15/02/2018 23:57:20 +00:00
      UserDataKeepAliveTimer.OnTimer: Keep-alive user stream ("kAisw7JrMW5okOtcRH4xOW4FtIY26qc1poydOFVBCdLQUNktfSqQcXuj89Fi").  [thread: 6]
[dbug] 15/02/2018 23:57:20 +00:00
      UserDataWebSocketManager.SubscribeAndStreamAsync: Streaming.  [thread: 5]
[info] 15/02/2018 23:57:20 +00:00
      BinanceWebSocketStream.StreamAsync: "wss://stream.binance.com:9443/ws/kAisw7JrMW5okOtcRH4xOW4FtIY26qc1poydOFVBCdLQUNktfSqQcXuj89Fi"
[dbug] 15/02/2018 23:57:20 +00:00
      BinanceHttpClient.RequestAsync: [PUT] "/api/v1/userDataStream?listenKey=kAisw7JrMW5okOtcRH4xOW4FtIY26qc1poydOFVBCdLQUNktfSqQcXuj89Fi"
[dbug] 15/02/2018 23:57:21 +00:00
      BinanceHttpClient: "{}"

however the following error is thrown, and none of the streams are subscribed:

ERROR: ITradeWebSocketClient: Controller failed.
   at BinanceBase4X.Utils.Logger.Log(String message, LogLevel level, String memberName, Int32 lineNumber) in F:\VS\BinanceBase\BinanceBase4X\BinanceBase4X\Utils\Logger.cs:line 53
   at BinanceBase4X.Utils.Writer.WriteBuffer(String text, BufferConsole bufferConsole, ConsoleColor colour, LogLevel logLevel, String memberName) in F:\VS\BinanceBase\BinanceBase4X\BinanceBase4X\Utils\Writer.cs:line 27
   at BinanceBase4X.Program.<>c.<Main>b__54_1(Object s, WebSocketManagerErrorEventArgs e) in F:\VS\BinanceBase\BinanceBase4X\BinanceBase4X\Program.cs:line 323
   at Binance.WebSocket.Manager.BinanceWebSocketManager.RaiseErrorEvent(IBinanceWebSocketClient client, Exception exception, String message)
   at Binance.Utility.RetryTaskController.<<Begin>b__5_0>d.MoveNext()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.Task.DelayPromise.Complete()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

if I step it through in debug, or place a Thread.Sleep() between each of the awaited calls in the first code block, it all works fine. Am I missing something? It doesn't feel like the "correct" solution to Thread.Sleeep() there...

**Comment by sonvister** [comment]
@pingu2k4, in the next release (**0.2.0-alpha35**) the automatic web socket client manager has been redesigned, in part, to avoid the unnecessary stream cancelling and beginning that occurs in a scenario like this (*without user intervention*).

But, with this iteration, the flag [`IsAutoStreamingDisabled`](https://github.com/sonvister/Binance/blob/v0.2.0-alpha34/src/Binance/WebSocket/Manager/IBinanceWebSocketManager.cs) is provided for users to disable the automatic streaming if they were to subscribe to multiple streams at once.

**Comment by sonvister** [comment]
@pingu2k4, could you determine if your use case has an issue with the latest release (*if this can be closed*)?
