### ISSUE TITLE
TaskCanceledException raised

### ISSUE THREAD

**Issue by pingu2k4** [sonvister/Binance#64]
So, occasionally when calling GetOrder or GetOpenOrders, I was getting the "Timestamp for this request is outside of the recvWindow" problem. It was taking 40 seconds + to return from the initial call.

Because of this, instead of not passing a value to recvWindow, I passes 10,000,000 to make sure it would be OK. (not sure if thats an acceptable work around to get it to always work..?)

However, when it called GetOpenOrders doing this, I had a different error. System.AggregateException: 'One or more errors occurred. (A task was canceled.)'
TaskCanceledException: A task was canceled.

Noting is put into the logfile, but here is the call:
[dbug] 21/02/2018 04:18:40 +00:00
      BinanceHttpClient.RequestAsync: [GET] "/api/v3/openOrders?symbol=BTCUSDT&recvWindow=10000000&timestamp=1519186720739&signature=#####"

The final entry to the logfile was at [dbug] 21/02/2018 04:19:47 +00:00, so execution continued for just over a minute (without the call returning), before it raised the error.

**Comment by sonvister** [comment]
@pingu2k4, the request either isn't reaching Binance within the recvWindow time or not making the round trip before the request timeout.

The `HttpClient` request timeout is set to 60 seconds (*the task canceled scenario*). When the request got through before the timeout you get the "it took too long" error from Binance. Increasing the recvWindow is the correct thing to do there, but anything beyond the HTTP request timeout won't do anything more for you.

I'll set the default HTTP request timeout to 90 seconds and also make it a configurable option, which should help *reduce* your errors.

**Comment by sonvister** [comment]
@pingu2k4, let me know if this has been resolved (*if this issue can be closed*).
