### ISSUE TITLE
0.2.0-alpha35: Exceptions Raised when Cancelling token for Aggregate Trade Socket

### ISSUE THREAD

**Issue by rakewell** [sonvister/Binance#65]
I seem to be getting a few exceptions when unsubscribing Aggregate Trade Updates. These exceptions are not propagated to the client and therefore do not get trapped by the client, they are just simply swallowed by the runtime. The reason I bring this up is because on one occasion, when the function ran to Unsubscribe and the Re-subscribe (because I needed to add another symbol to the subscription), the aggregate trade socket stopped sending trade updates even though the socket was still connected. The logs didn't show any errors or anything unusual. I can only suspect that it was something to do with the unhandled exceptions below. These exceptions always get raised whenever the unsubscribing takes place. Off course, the cancel exceptions are expected but I'm not sure if the other ones are interfering with the socket when re-subscription takes place.  I have tried to add more information to the exceptions by making the runtime break and then copy the details (these are in brackets), see below.

here is the unsubscribing code:

```
    Private Sub UnSubscibeAllTradeUpdatesManaged()
        If Me.m_BinanceAggregateTradeSocketCancel IsNot Nothing Then

            Me.m_BinanceAggregateTradeSocketCancel.Cancel() 'this will cancel all streams 

            Me.m_BinanceAggregateTradeSocketCancel.Dispose()
            Me.m_BinanceAggregateTradeSocketCancel = Nothing

            Me.m_BinanceAggregateTradeSocketManager.Unsubscribe()

        End If
    End Sub
```

here is the initialisation code for the AggregateTradeSocket:

```
        Dim AggregateTradeSocketLoggerFactory As ILoggerFactory = New Microsoft.Extensions.Logging.LoggerFactory()
        AggregateTradeSocketLoggerFactory.AddFile("logs/Binance/" & Me.m_TradingAccountID & " Aggregate Trade Socket - ApiLogger Debug." & Date.Now.ToSortableDate & ".txt", LogLevel.Trace)

        'initialise Stream  & loggers      
        Dim AggregateTradeSocketStreamClientLogger As New Logger(Of DefaultWebSocketClient)(AggregateTradeSocketLoggerFactory)
        Dim AggregateTradeWebSocketStreamLogger As New Logger(Of BinanceWebSocketStream)(AggregateTradeSocketLoggerFactory)

        Me.m_BinanceAggregateTradeSocketClient = New DefaultWebSocketClient(AggregateTradeSocketStreamClientLogger)
        Me.m_BinanceAggregateTradeSocketStream = New BinanceWebSocketStream(m_BinanceAggregateTradeSocketClient, AggregateTradeWebSocketStreamLogger)


        'initialise objects for the AggregateTradeDataWebSocketClientManager & loggers
        Dim BinanceAggregateTradeSocketManagerLogger As New Logger(Of AggregateTradeWebSocketClientManager)(AggregateTradeSocketLoggerFactory)
        Dim BinanceAggregateTradeClientLogger As New Logger(Of AggregateTradeClient)(AggregateTradeSocketLoggerFactory)

        Me.m_BinanceAggregateTradeClient = New AggregateTradeClient(BinanceAggregateTradeClientLogger)
        Me.m_BinanceAggregateTradeStreamController = New BinanceWebSocketStreamController(Me.m_BinanceApi, m_BinanceAggregateTradeSocketStream, AddressOf BinanceAggregateTradeStreamControllerExceptionHandler)
        Me.m_BinanceAggregateTradeSocketManager = New AggregateTradeWebSocketClientManager(m_BinanceAggregateTradeClient, m_BinanceAggregateTradeStreamController, BinanceAggregateTradeSocketManagerLogger)

        AddHandler Me.m_BinanceAggregateTradeSocketClient.Close, AddressOf Me.m_BinanceSocketAggregateTradeStreamClient_Close
        AddHandler Me.m_BinanceAggregateTradeSocketClient.Open, AddressOf Me.m_BinanceSocketAggregateTradeStreamClient_Open

        AddHandler Me.m_BinanceAggregateTradeSocketClient.Message, AddressOf Me.m_BinanceAggregateTradeStreamClient_Message
```

here are the exceptions called every time an unsubscription takes place
```

Exception thrown: 'System.ObjectDisposedException' in System.dll
(System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.')

Exception thrown: 'System.IO.IOException' in System.dll
(: 'Unable to read data from the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'..')

Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Exception thrown: 'System.OperationCanceledException' in System.dll
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in mscorlib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in Binance.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in mscorlib.dll


```

**Comment by sonvister** [comment]
@rakewell, just looking at your unsubscribe code and assuming the token is the source of the `ObjectDisposedException`, you are canceling then immediately disposing of the cancellation token. It is best to wait for the StreamAsync() `Task` to complete (*or at least add some delay after cancel*) before disposing of the token.

**Comment by rakewell** [comment]
I changed the code to just these two lines:

```
            Me.m_BinanceAggregateTradeSocketCancel.Cancel() 'this will cancel all streams 
            Me.m_BinanceAggregateTradeSocketManager.Unsubscribe()
```

also tried:
```

            Me.m_BinanceAggregateTradeSocketCancel.Cancel() 'this will cancel all streams 

            Thread.Sleep(1000)
            Me.m_BinanceAggregateTradeSocketManager.Unsubscribe()
```

and:

```
            Me.m_BinanceAggregateTradeSocketManager.Unsubscribe()
            Thread.Sleep(1000)

            Me.m_BinanceAggregateTradeSocketCancel.Cancel() 'this will cancel all streams 

```

and just:

`Me.m_BinanceAggregateTradeSocketManager.Unsubscribe()
`

but all changes still getting the same exceptions:


```
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Exception thrown: 'System.OperationCanceledException' in System.dll
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in mscorlib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in Binance.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in mscorlib.dll


```

**Comment by sonvister** [comment]
@rakewell, also, in 0.2.0-alpha35 you are not required to cancel streaming before subscribe/unsubscribe when using a `IJsonStream` directly and canceling was never required when using a *manager*.

**Comment by sonvister** [comment]
@rakewell, I've updated the `BinanceTradeHistory` sample application to best approximate what you may be trying to do here (*I use DI and a cache, but tested with only the manager too*). So far, I haven't seen any exceptions. I don't know if my use case matches yours or to what extent the code changes I've made post 0.2.0-alpha35 have improved the situation. But, you are welcome to build the latest source code and test before the next release....

**Comment by rakewell** [comment]
I did have a look at your sample application and there was no such exceptions thrown when calling Unsubscribe on the AggregateTradeCache object. However when calling it directly on the manager i.e.

`manager.Unsubscribe() `

instead of 

`cache.Unsubscribe()`

you get an exceptions:

`Exception thrown: 'System.InvalidOperationException' in Binance.dll`

In debuging the source code (in my application) I see that it stops on the following function on the BufferedJsonStream object. The exception is thrown on the _cts.Cancel(); line:

```
        private void AbortStreaming()
        {
            _stopwatch.Restart();

            try
            {
                if (!_cts?.IsCancellationRequested ?? false)
                {
                    _cts.Cancel();
                }
            }
            catch (Exception e)
            {
                Logger?.LogError(e, $"{GetType().Name}.{nameof(AbortStreaming)}: Failed.  [thread: {Thread.CurrentThread.ManagedThreadId}]");
            }
        }
```

and the exception that is raised it.

```
Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
```

Should I be calling the Unsubscribe on another object?

**Comment by sonvister** [comment]
@rakewell, you should be calling unsubscribe on the object that you called subscribe.

I have since added lock around the cancellation token source, which might help (*you may wish to try the 0.2.0-alpha36 release or latest source code*). I do not get any `InvalidOperationException` when using the sample application (*with only the manager*) as you describe. So, unless I can reproduce or otherwise know what is happening in your scenario... 🤷‍♂️

It would be nice to understand, but it shouldn't be causing any abnormal behavior as long as the streaming is canceled. Maybe the fix is to remove the logging, although I'd rather understand what is happening (*which is why the logging is there in the first place*).

**Comment by rakewell** [comment]
@sonvister, interesting that it doesn't come up on your end. Keep in mind these are exceptions caught by the runtime and not propagated (and therefore will not show up in the log file). If you edit your exceptions settings and select true for ObjectDisposedException and InvalidOperationException then it will stop when the exception is thrown.

![snip20180225_48](https://user-images.githubusercontent.com/35868094/36638171-73336978-1a41-11e8-928d-528e95a78a59.png)

**Comment by sonvister** [comment]
@rakewell, if it is not propagated why do you care about it? Why should I care about it?

**Comment by rakewell** [comment]
as mentioned in the opening post only because there was a fault with the aggregate stream but I think that it might have something to do with unsubscribe/resubscribe.

**Comment by rakewell** [comment]
I will close this issue but will keep an eye an events swallowed by the runtime.
