### ISSUE TITLE
Keep Alive failing - not restarting websocket.

### ISSUE THREAD

**Issue by pingu2k4** [sonvister/Binance#72]
Hey, not entirely sure if this has been resolved in a later release (I'm still on Alpha-30 - Have been running in almost non stop so not really had a chance to upgrade etc yet).

I did have a look at commits etc, couldn't  find anything that I thought would fix this.

So I looked back in logs and saw the following:

[dbug] 03/03/2018 17:04:05 +00:00
      UserDataKeepAliveTimer.OnTimer: Keep-alive user stream ("3BMknTSinuzBQeuwPgbARhALrXAaAMGoaEVbl5nu7945d98eppuSV7KpAJgc").  [thread: 13]
[dbug] 03/03/2018 17:04:05 +00:00
      BinanceHttpClient.RequestAsync: [PUT] "/api/v1/userDataStream?listenKey=BLAH"
[fail] 03/03/2018 17:04:09 +00:00
      UserDataKeepAliveTimer.OnTimer: Failed to ping user data stream.
      (exception: "[InternalServerError]: 'Server Error' - An unknown error occured while processing the request. (-1000)")

And then the next time it tried to keep-alive, the following was given

[dbug] 03/03/2018 17:34:05 +00:00
      UserDataKeepAliveTimer.OnTimer: Keep-alive user stream ("BLAH").  [thread: 15]
[fail] 03/03/2018 17:34:06 +00:00
      UserDataKeepAliveTimer.OnTimer: Failed to ping user data stream.
      (exception: "[BadRequest]: 'Bad Request' - This listenKey does not exist. (-1125)")

As a result, I was no longer recieving data through the websocket, but it had not noticed or restarted itself etc.

**Comment by sonvister** [comment]
@pingu2k4, can you determine if there is an issue with the latest release (*if this can be closed*)?
