### ISSUE TITLE
Watchdog keeps closing streams after 1 hour

### ISSUE THREAD

**Issue by pingu2k4** [sonvister/Binance#74]
Hey,

Since I posted my last issue I thought it best to upgrade, as I witnessed that problem a second time.

I made changes to have it still run, but now after an hour, watchdog timers close all my streams, even though they were recieving data.

I subscribe to aggregate trades, as well as user data stream. 
When looking at the samples from the latest version, it appeared that I couldn't use RetryTaskController the same way anymore. Anyway, I have all my Live calls subscribe as follows:

Program.clientManager.AggregateTradeClient.Subscribe(symbol, action);

Before calling, I am doing:
clientManager = serviceProvider.GetService<IBinanceWebSocketClientManager>();
            clientManager.Error += (s, e) =>
            {
                Writer.WriteBuffer("ERROR: " + e.Exception.Message, ConsoleColor.Red, Logger.LogLevel.ERROR);
            };

and on service provider, I have:

                 .AddBinance(useSingleCombinedStream: true)

What should I be doing to not have my agg trades conn closed by watchdog timer?

Here are logs for example:

[dbug] 05/03/2018 00:59:48 +00:00
      BinanceHttpClient.RequestAsync: [POST] "/api/v3/order?symbol=BTCUSDT&side=BUY&type=LIMIT&newOrderRespType=FULL&quantity=0.0048&price=11378&timeInForce=GTC&recvWindow=10000000&timestamp=1520211586813&signature=8DE1602959B999B5C015FEEB041E2844C76E4C65C9C99A0CE6483F6E21B617D3"
[info] 05/03/2018 01:28:10 +00:00
      TradeWebSocketClientManager: Watchdog timer aborting stream controller (no data received in 60 minutes).  [thread: 6]
[info] 05/03/2018 01:28:10 +00:00
      SymbolStatisticsWebSocketClientManager: Watchdog timer aborting stream controller (no data received in 60 minutes).  [thread: 26]
[info] 05/03/2018 01:28:10 +00:00
      DepthWebSocketClientManager: Watchdog timer aborting stream controller (no data received in 60 minutes).  [thread: 24]
[dbug] 05/03/2018 01:28:10 +00:00
      DefaultWebSocketClient.StreamAsync: Task complete.  [thread: 22]
[info] 05/03/2018 01:28:10 +00:00
      BinanceWebSocketStream.StreamActionAsync: End streaming...
      (wss://stream.binance.com:9443/stream?streams=vkONqliCmaeh4ySQUkCFvgSlOYiwDyXRBdEVNOJQcU22fofmGZInNfikE6zF/btcusdt@aggTrade)
[dbug] 05/03/2018 01:28:10 +00:00
      BinanceWebSocketStream.StreamAsync: Streaming complete.  [thread: 22]
[dbug] 05/03/2018 01:28:10 +00:00
      RetryTaskController: Task complete.  [thread: 22]
[info] 05/03/2018 01:28:10 +00:00
      CandlestickWebSocketClientManager: Watchdog timer aborting stream controller (no data received in 60 minutes).  [thread: 23]
[dbug] 05/03/2018 01:28:22 +00:00
      UserDataWebSocketStreamControl.HandleTimer: Keep-alive user stream (vkONqliCmaeh4ySQUkCFvgSlOYiwDyXRBdEVNOJQcU22fofmGZInNfikE6zF).  [thread: 5]
[dbug] 05/03/2018 01:28:22 +00:00
      BinanceHttpClient.RequestAsync: [PUT] "/api/v1/userDataStream?listenKey=vkONqliCmaeh4ySQUkCFvgSlOYiwDyXRBdEVNOJQcU22fofmGZInNfikE6zF"
[dbug] 05/03/2018 01:58:22 +00:00
      UserDataWebSocketStreamControl.HandleTimer: Keep-alive user stream (vkONqliCmaeh4ySQUkCFvgSlOYiwDyXRBdEVNOJQcU22fofmGZInNfikE6zF).  [thread: 11]
[dbug] 05/03/2018 01:58:22 +00:00
      BinanceHttpClient.RequestAsync: [PUT] "/api/v1/userDataStream?listenKey=vkONqliCmaeh4ySQUkCFvgSlOYiwDyXRBdEVNOJQcU22fofmGZInNfikE6zF"
[info] 05/03/2018 02:28:00 +00:00
      AggregateTradeWebSocketClientManager: Watchdog timer aborting stream controller (no data received in 60 minutes).  [thread: 6]
[info] 05/03/2018 02:28:10 +00:00
      SymbolStatisticsWebSocketClientManager: Watchdog timer aborting stream controller (no data received in 60 minutes).  [thread: 6]
[info] 05/03/2018 02:28:10 +00:00
      CandlestickWebSocketClientManager: Watchdog timer aborting stream controller (no data received in 60 minutes).  [thread: 23]
[info] 05/03/2018 02:28:10 +00:00
      DepthWebSocketClientManager: Watchdog timer aborting stream controller (no data received in 60 minutes).  [thread: 24]
[info] 05/03/2018 02:28:10 +00:00
      TradeWebSocketClientManager: Watchdog timer aborting stream controller (no data received in 60 minutes).  [thread: 5]
[dbug] 05/03/2018 02:28:22 +00:00
      UserDataWebSocketStreamControl.HandleTimer: Keep-alive user stream (vkONqliCmaeh4ySQUkCFvgSlOYiwDyXRBdEVNOJQcU22fofmGZInNfikE6zF).  [thread: 6]

Also, I have logging set to trace, but no longer see any data being printed to the log from agg trade like I used to. It is reciving for the first hour though, as the values are pushed through my code.

**Comment by sonvister** [comment]
@pingu2k4, each manager has a `IWatchdogTimer` that looks for data to that manager. Each watchdog has an `Interval` that can be increased. When using a single combined stream, one manager may close the stream of another manager (*although I would not expect to see each manager log 'aborting' in that case*).

**Comment by pingu2k4** [comment]
I've been testing with it in debug mode, it appears that the line
`.AddBinance(useSingleCombinedStream: true)`
was causing the problem. When I leave this blank, so it defaults to false, the watchdog timers still go off but they do not cancel the streams which are still receiving data.

**Comment by sonvister** [comment]
@pingu2k4, now that the `IWatchdogTimer` has been relocated, could you determine if this is an issue with the latest release (*if this can be closed*)?

**Comment by alikalfaoglu** [comment]
Not using combined streams and still having issue.
----------------------------------------------------------
info: Binance.Utility.BinanceWebSocketStreamController[0]
      JsonStreamController: Watchdog timer restarting stream controller (no data received in 60 minutes).  [thread: 25]
info: Binance.Utility.BinanceWebSocketStreamController[0]
      JsonStreamController: Watchdog timer restarting stream controller (no data received in 60 minutes).  [thread: 4]
info: Binance.Utility.BinanceWebSocketStreamController[0]
      JsonStreamController: Watchdog timer restarting stream controller (no data received in 60 minutes).  [thread: 16]
info: Binance.Utility.BinanceWebSocketStreamController[0]
      JsonStreamController: Watchdog timer restarting stream controller (no data received in 60 minutes).  [thread: 64]
info: Binance.Utility.BinanceWebSocketStreamController[0]
      JsonStreamController: Watchdog timer restarting stream controller (no data received in 60 minutes).  [thread: 23]
info: Binance.Utility.BinanceWebSocketStreamController[0]
      JsonStreamController: Watchdog timer restarting stream controller (no data received in 60 minutes).  [thread: 72]
warn: Binance.WebSocket.UserDataWebSocketStreamControl[0]
      UserDataWebSocketStreamControl.HandleTimer: Failed to ping user data stream (1st attempt).
Binance.BinanceHttpException: [BadRequest]: 'Bad Request' - This listenKey does not exist. (-1125)
   at Binance.BinanceHttpClient.<RequestAsync>d__25.MoveNext() in D:\Source\GitHub\Private\DayTrader\src\Binance\Api\BinanceHttpClient.cs:line 215
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.BinanceHttpClientExtensions.<UserStreamKeepAliveAsync>d__29.MoveNext() in D:\Source\GitHub\Private\DayTrader\src\Binance\Extensions\BinanceHttpClientExtensions.cs:line 1159
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.BinanceApi.<UserStreamKeepAliveAsync>d__51.MoveNext() in D:\Source\GitHub\Private\DayTrader\src\Binance\Api\BinanceApi.cs:line 833
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.WebSocket.UserDataWebSocketStreamControl.<HandleTimer>d__22.MoveNext() in D:\Source\GitHub\Private\DayTrader\src\Binance\WebSocket\Manager\UserDataWebSocketStreamControl.cs:line 232
warn: Binance.WebSocket.UserDataWebSocketStreamControl[0]
      UserDataWebSocketStreamControl.HandleTimer: Failed to ping user data stream (2nd attempt).
Binance.BinanceHttpException: [BadRequest]: 'Bad Request' - This listenKey does not exist. (-1125)
   at Binance.BinanceHttpClient.<RequestAsync>d__25.MoveNext() in D:\Source\GitHub\Private\DayTrader\src\Binance\Api\BinanceHttpClient.cs:line 215
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.BinanceHttpClientExtensions.<UserStreamKeepAliveAsync>d__29.MoveNext() in D:\Source\GitHub\Private\DayTrader\src\Binance\Extensions\BinanceHttpClientExtensions.cs:line 1159
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.BinanceApi.<UserStreamKeepAliveAsync>d__51.MoveNext() in D:\Source\GitHub\Private\DayTrader\src\Binance\Api\BinanceApi.cs:line 833
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.WebSocket.UserDataWebSocketStreamControl.<HandleTimer>d__22.MoveNext() in D:\Source\GitHub\Private\DayTrader\src\Binance\WebSocket\Manager\UserDataWebSocketStreamControl.cs:line 257
Unsubscribe old listen key... jSSbft9Iv8viGiJ01742BC7y09c6dWbCOT2mUMRtTtuRizXF45IbiHkjItiW
Subscribe to new listen key... MlJjTsbGoLGPx2Fuc8KdpwuhMozRaD48jxulyVxUKgPVrVQ3nMQBbO5S7to7
