### ISSUE TITLE
0.2.0-alpha40: AggregateTradeWebSocketClient.Unsubscribe() doesn't close the socket

### ISSUE THREAD

**Issue by rakewell** [sonvister/Binance#76]
This can be tested on your demo console application:

Test console application using following commands:

live aggtrades btcusdt
live aggtrades btcusdt off

console output (after off):
```
info: Binance.WebSocket.DefaultWebSocketClient[0]
      DefaultWebSocketClient.OnClose: Web Socket CLOSED.
info: Binance.WebSocket.BinanceWebSocketStream[0]
      WebSocketStream.StreamActionAsync: End streaming...
      "wss://stream.binance.com:9443/ws/btcusdt@aggTrade"
```

Make the following changes to LiveAggregateTrades:

Change the line:

`Program.ClientManager.AggregateTradeClient.Unsubscribe(symbol);`

to

`Program.ClientManager.AggregateTradeClient.Unsubscribe();`

run the program with the same commands:
live aggtrades btcusdt
live aggtrades btcusdt off

console output (after off):
` ...live aggregate trades feed DISABLED for symbol: btcusdt`

there is no log indicating that the web socket is closed and the websocket IsOpen and IsStreaming properties return true.

**Comment by sonvister** [comment]
@rakewell, thanks, I see the issue and have a fix.

**Comment by rakewell** [comment]
thanks @sonvister, works great now.
