### ISSUE TITLE
how to handle gateway timeout (no message)

### ISSUE THREAD

**Issue by pingu2k4** [sonvister/Binance#77]
Tried placing a sell order, after having been running my bot for quite a long time and placing a sell order failed with:

Message	"[GatewayTimeout]: '[NO REASON]' - [NO MSG] [NO CODE"

Luckily, I saw it about 3 minutes after it happened :) But, what should I do to circumvent this? Is there something this wrapper could do or should I be looking at encase each rest call in a try catch, and handling this unknown error myself?

Its quite an annoying one - I believe I have seen this one in the past, and order has actually successfully been placed, however this time the order was not placed. So the lack of information returned is quite the problem.

**Comment by sonvister** [comment]
@pingu2k4, how to handle HTTP 504 is documented (#66).

**Comment by sonvister** [comment]
I will update `BinanceUnknownStatusException` to reiterate the following as the error message: "[It is important to NOT treat this as a failure; the execution status is UNKNOWN and could have been a success.](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md)"
