### ISSUE TITLE
Question: How to get qty of "end" symbol in a market order?

### ISSUE THREAD

**Issue by betimd** [sonvister/Binance#79]
When I sell XRP to ETH (or BTC, BNB...) with a market order and get the result back that order succeeded I get amount of my start symbol (in this case XRP), but what I need is to get end symbol. Say, I sold 100 XRP to ETH, what's the amount of ETH I got from 100 XRP?
I checked Trades API as well but still I miss that info. In Binance - Order History I see that amount, ex. 0.04502440 ETH (for 40 XRP).

**Comment by sonvister** [comment]
@betimd, the returned `Order` should have one or more `Fill` instances in the `Order.Fills` property with `Fill.Quantity`.

Reference: [Official Binance API](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade)
