### ISSUE TITLE
AccountInfoCache

### ISSUE THREAD

**Issue by raphaotten** [sonvister/Binance#81]
Hi,

As I couldn't find an example for AccountInfoCache and can't get it working properly in the newer versions (since SubscribeAndStream disappeared): Could you give a short example on how to create the AccountInfoCache and Subscribing (&Streaming?).
In accountInfoCache.Subscribe() I need to pass the listenKey, but aren't these are managed internally by the library? Which one to pass? Only way I found was to get one using "await api.UserStreamStartAsync(user);" but then the Update event never fired...

Thank you very much,
Raphael

**Comment by sonvister** [comment]
@raphaotten, there are no examples for `AccountInfoCache`. The user data relevant examples are in the `AccountBalancesExample.cs` and `OrderBookCacheAccountBalanceExample.cs` files of the `BinanceConsoleApp` sample app. These examples demonstrate the use of `IUserDataWebSocketManager` which manages the listen keys.

**Comment by raphaotten** [comment]
Thanks a lot!!
