### ISSUE TITLE
ToCandlestickInterval: interval not supported: 6h

### ISSUE THREAD

**Issue by sguryev** [sonvister/Binance#82]
`CandlestickInterval.Hours_6` can be converted to string:
https://github.com/sonvister/Binance/blob/da2967a181212fda937a28ed6fcdd284f0778966/src/Binance/Extensions/CandlestickIntervalExtensions.cs#L25

But it doesn't support  the opposite conversion:
https://github.com/sonvister/Binance/blob/da2967a181212fda937a28ed6fcdd284f0778966/src/Binance/Extensions/StringExtensions.cs#L41

Result - there is no way to subscribe for 6h interval.
Is it by design?

**Comment by sonvister** [comment]
@sguryev, thanks for mentioning.

**Comment by sguryev** [comment]
@sonvister do you want me to prepare the PR? Ooops. it looks like I'm late. Sorry
