### ISSUE TITLE
'Server Error' - An unknown error occured while processing the request. (-1000)

### ISSUE THREAD

**Issue by turgayacar** [sonvister/Binance#85]
Greetings;
I have an error. not solve please help for us.

Binance.BinanceHttpException: [InternalServerError]: 'Server Error' - An unknown error occured while processing the request. (-1000)
   konum: Binance.BinanceHttpClient.<RequestAsync>d25.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: Binance.BinanceHttpClientExtensions.<GetOrderAsync>d15.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: Binance.BinanceApi.<GetOrderAsync>d36.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   konum: TraderCornerBroker.Helpers.Binance.BinanceHelper.<StatusUpdate>d12.MoveNext() D:\PROGRAMLAMA\PROJE\Global Trade\TraderCornerBroker\TraderCornerBroker\Helpers\Binance\BinanceHelper.cs içinde: satır 362

**Comment by sonvister** [comment]
@turgayacar, there is nothing I can do. For such issues there is the [Binance Official API Telegram](https://t.me/binance_api_english). It looks like others are/were having the same issue.

Reference: [Error codes for Binance](https://github.com/binance-exchange/binance-official-api-docs/blob/master/errors.md#-1000-unknown)

**Comment by turgayacar** [comment]
Error this.
Order order =  Api.GetOrderAsync(Globals.Ayarlar.BinanceUser, item.Symbol, item.ServerId, Globals.Ayarlar.ServerSync).ConfigureAwait(true).GetAwaiter().GetResult();

**Comment by sonvister** [comment]
If there is anything here other than a temporary issue with Binance servers please reopen the issue.
