### ISSUE TITLE
failed to parse JSON api response

### ISSUE THREAD

**Issue by pavlexander** [sonvister/Binance#9]
upon a call of _GetOpenOrdersAsync_
There is an existing stop-limit order for a combination. Seems like parser has troubles with it..

> There was an exception: System.AggregateException: One or more errors occurred. (BinanceApi.GetOpenOrdersAsync failed to parse JSON api response: "[{"symbol":"BTSBNB","orderId":1240076,"clientOrderId":"suD1UBfBadgTMr8TaN57Up","price":"0.16120000","origQty":"70.00000000","executedQty":"0.00000000","status":"NEW","timeInForce":"GTC","type":"TAKE_PROFIT_LIMIT","side":"SELL","stopPrice":"0.16100000","icebergQty":"0.00000000","time":1513782457496,"isWorking":false}]") ---> Binance.Api.BinanceApiException: BinanceApi.GetOpenOrdersAsync failed to parse JSON api response: "[{"symbol":"BTSBNB","orderId":1240076,"clientOrderId":"suD1UBfBadgTMr8TaN57Up","price":"0.16120000","origQty":"70.00000000","executedQty":"0.00000000","status":"NEW","timeInForce":"GTC","type":"TAKE_PROFIT_LIMIT","side":"SELL","stopPrice":"0.16100000","icebergQty":"0.00000000","time":1513782457496,"isWorking":false}]" ---> System.Exception: Failed to convert order type: "TAKE_PROFIT_LIMIT"
>    at Binance.StringExtensions.ConvertOrderType(String type)
>    at Binance.Api.BinanceApi.FillOrder(Order order, JToken jToken)
>    at Binance.Api.BinanceApi.<GetOpenOrdersAsync>d__25.MoveNext()
>    --- End of inner exception stack trace ---

**Comment by sonvister** [comment]
Please update to Binance **v0.2.0-alpha.5+** where the new order types (including TAKE_PROFIT_LIMIT) are supported. Thanks.
