### ISSUE TITLE
Problem GetPriceAsync

### ISSUE THREAD

**Issue by artyomgrishchenko** [sonvister/Binance#90]
Hello! I found that the method GetPriceAsync returns incorrect data. Check, please.

Assembly Binance, Version=0.2.0.53
public virtual Task<SymbolPrice> GetPriceAsync(string symbol, CancellationToken token = default)

**Comment by sonvister** [comment]
Hi @artyomgrishchenko,

1. What symbol or symbols do you believe return incorrect data?
1. Have you compared values from `GetPriceAsync()` with results from https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT (*substituting your symbol*)? I believe this data is updated every second based on the price ticker stream push rate.

If the data from the official (web) API is incorrect, please inform the Binance API Telegram group.

**Comment by artyomgrishchenko** [comment]
1. I do not remember exactly, maybe it was LRCBTC. But I think that it does
not matter...
2. No, I determined that the data is incorrect because I had an open order,
and it did not work, although the method returned the price higher than it.

>
Yes, in the end, I think the problem was in the API Binance

**Comment by sonvister** [comment]
1. It may not matter, but it might, it could help someone reproduce the issue, etc.
1. More explanation/details would help someone trying to reproduce/understand the issue... was it a STOP, LIMIT, BUY or SELL order, price(s), timestamps, etc.

So, at the moment, I don't see anything for me to fix (*LRCBTC price is consistent with the Binance website*).

**Comment by artyomgrishchenko** [comment]
Thank you very much, the main thing is that in the calls to api functions
everything is fine. If there are still problems, I'll try to fix all the
data more precisely

2018-05-08 18:40 GMT+03:00 sonvister <notifications@github.com>:
