### ISSUE TITLE
Copy-Paste typo?

### ISSUE THREAD

**Issue by sguryev** [sonvister/Binance#91]
https://github.com/sonvister/Binance/blob/e9c364cede3d3f530e17d1d50f6b403169f4b162/src/Binance/Extensions/CandlestickIntervalExtensions.cs#L33

**Comment by sonvister** [comment]
Probably. Thanks.

**Comment by sguryev** [comment]
off-top: I have sent you a direct message in the twitter. I have a couple of questions. If twitter is not a good place - please provide the alternative one. thank you!
