### ISSUE TITLE
New Symbols Update

### ISSUE THREAD

**Issue by turgayacar** [sonvister/Binance#92]
Greetings;

I am working on the Symbol object in the library directly. I can not process new incoming symbols. I tried UpdateCache though, but I was not successful. Obviously, it does not really work to use it this way. What is the way to do this? A sample code block and description would be nice. (The wiki update is very good). An update that can be used on new symbols will come in a nutshell?
Best Regards.

**Comment by sonvister** [comment]
@turgayacar, perhaps the changes in [0.2.0-beta4](https://github.com/sonvister/Binance/releases/tag/v0.2.0-beta4) will give you the behavior you are expecting (*static assets and symbols are now redirected to cache values*).

```C#
// Update Symbol and Asset cache:
await Symbol.UpdateCacheAsync(api, token);
```
