### ISSUE TITLE
Beta 5 Symbol Issue

### ISSUE THREAD

**Issue by turgayacar** [sonvister/Binance#94]
Greetings;
I want to set Symbol by string;
Example =  Symbol sym = "BTCUSDT";
but push error this update. 
How to fix it?
Need set from string asset or symbol. And very useful.

**Comment by sonvister** [comment]
@turgayacar, the implicit conversion of `string` to `Symbol` was replaced with `Symbol.Cache.Get()` in [0.2.0-beta4](https://github.com/sonvister/Binance/releases/tag/v0.2.0-beta4) (issue #89) and a cache abstraction layer was added.

So, `Symbol sym = "BTCUSDT";` is now `Symbol sym = Symbol.Cache.Get("BTCUSDT");`

The code is not as concise, but it resolves #89 and makes it clear that the `Symbol` is being pulled from the cache.

**Comment by turgayacar** [comment]
Oh Thanks.
Best Regards.
