### ISSUE TITLE
SymbolGenerator fails under different locale

### ISSUE THREAD

**Issue by evo11x** [sonvister/Binance#96]
When running the Symbol Code Generator on a computer with a locale which have , comma as decimal separator it generates the prices for each symbol with a comma , instead of point which ends up with a symbols file which cannot be compiled because it treats each decimal separator as a new parameter.

Adding CultureInfo us = new CultureInfo("en-US"); does not solve the problem

**Comment by sonvister** [comment]
@evo11x, let me know if these changes work for you. Thanks.

**Comment by evo11x** [comment]
Yes it work now! Thanks!
