### ISSUE TITLE
problem with KEY coin 

### ISSUE THREAD

**Issue by oskarhub** [sonvister/Binance#99]
Are the coins symbols updated dynamically from binance (I think no, because in Symbol.cs there is no KEYBTC pair),  Im receiving an error trying to place buy order for this pair  KEY and BTC is a new coin in binance exchange. 
would you update symbols.cs or something, What could I do?  thanks  (btw Im using latest version)

**Comment by sonvister** [comment]
@oskarhub, ["Binance adds new traiding pairs regularly, it is not a goal of this project to create a new release just to update the static assets and symbols."](https://github.com/sonvister/Binance/wiki#assets-and-symbols)

If there is no predefined static symbol for a new trading pair you must use the string equivalent (e.g. "KEYBTC") or update the `Symbol` cache and get the `Symbol` from the cache using the string equivalent.

**Comment by oskarhub** [comment]
Im using "KEYBTC" already, this is the code (but is almost your sample code). with "update the symbol cache" you mean that I should modify and recompile your code (sorry Im kind of a noob)?
 ```
public async Task PlaceBuyOrder(string Simbolo, Decimal Quantity, Decimal Price)
        {
            using (var user = new BinanceApiUser(apikey, secretkey))
            {
                Simbolo = Simbolo.Replace("_", "");
                var clientOrder = new LimitOrder(user)
                {
                    Symbol = Simbolo,
                    Side = OrderSide.Buy,
                    Quantity = Quantity,
                    Price = Price
                };
                try
                {
                    clientOrder.Validate();
                    await api.PlaceAsync(clientOrder);
                }
                catch (Exception e)
                {
                    MessageBox.Show($"Limit Buy Order Failed: \"{e.Message}\"");
                }
            }
        }
```

**Comment by sonvister** [comment]
@oskarhub, *assuming* you are getting the `ArgumentException`: "The symbol (KEYBTC) is not recognized."

...The exception is caused by `clientOrder.Validate()` not order placement. The `ClientOrder` can only be validated if there is `Symbol` information available. You can either remove this line or update the symbol cache.

["To update the assets and symbols at runtime, use Symbol.UpdateCacheAsync(api)."](https://github.com/sonvister/Binance/wiki#assets-and-symbols)

**Comment by oskarhub** [comment]
it's ok now  it's only that when you said "update the Symbol cache"  I thought that I manually edit source code and compile LOL, I read the documentation and used the function and it's fine now. 
thanks!!!
